// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxmquwowkapktbukrekx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bXF1d293a2Fwa3RidWtyZWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTgyMzMsImV4cCI6MjA1OTUzNDIzM30.1sGLIGiWuBJtYpgzn9JhaJcdFsvUMtfJmq9-QGvIdUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);